### PR TITLE
Fix TorpedoStore fire logic

### LINKED ISSUE #3: Static analysis issues in TorpedoStore
Static analysis(SonarCloud) reported the following issues:
image

### PR DESCRIPTION
**Pull request by IAmBod**
Fix #3

### CODE REVIEW

File: src/main/java/hu/bme/mit/spaceship/TorpedoStore.java [hunk 1]
```diff
@@ -30,22 +32,18 @@ public TorpedoStore(int numberOfTorpedos){
...
 
     if (r >= FAILURE_RATE) {
       // successful firing
-      this.torpedoCount =- numberOfTorpedos;
+      this.torpedoCount -= numberOfTorpedos;
       success = true;
-    } else {
-      // simulated failure
-      success = false;
     }
```
Comment (IAmBod) [inline src/main/java/hu/bme/mit/spaceship/TorpedoStore.java]: Remove empty line

**Review by IAmBod — COMMENTED** [review]
Apply formatting suggestions
